Services:
   - type: web
     Name: discord-key-bot
     env: python
     plan: free
     buildCommand: pip install -r requirements.txt
     startCommand: python3 bot.py
     envVars:
       - key: BOT_TOKEN
         sync: false
       - key: PYTHON_VERSION
         value: 3.12.4
       - key: GUILD_ID
         Value: 1402622761246916628
     healthCheckPath: /
